import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  Query,
  Req,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiBody,
  ApiCreatedResponse,
  ApiForbiddenResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { Role } from '@prisma/client';
import { JwtAuthGuard } from '../../../common/auth/guards/jwt-auth.guard';
import { RolesGuard } from '../../../common/auth/guards/roles.guard';
import { Roles } from '../../../common/auth/roles.decorator';
import { CreateInvoiceTemplateDto } from '../dto/create-invoice-template.dto';
import {
  DeleteInvoiceTemplateResponseDto,
  InvoiceTemplateResponseDto,
} from '../dto/invoice-template-response.dto';
import { InvoiceTemplateQueryDto } from '../dto/invoice-template-query.dto';
import { UpdateInvoiceTemplateDto } from '../dto/update-invoice-template.dto';
import { InvoiceTemplatesService } from '../services/invoice-templates.service';

const createInvoiceTemplateExample = {
  organizationId: 'cm9z9u0g30000r4v0h8x8a7na',
  key: 'DEFAULT_PAYROLL_INVOICE',
  name: 'Default Payroll Invoice Template',
  headerHtml: '<h1>Payroll Invoice</h1>',
  bodyHtml:
    '<div>Invoice No: {{invoiceNumber}}</div><div>Employee: {{employeeName}}</div><div>Total: {{grossAmount}}</div>',
  footerHtml: '<div>Generated by FlowForce HRM</div>',
  css: '.invoice { font-family: Arial; }',
  variables: {
    invoiceNumber: 'Invoice number',
    employeeName: 'Employee full name',
    grossAmount: 'Invoice total amount',
  },
  isDefault: true,
  isActive: true,
};

const invoiceTemplateResponseExample = {
  id: 'cm9z9u0g30000r4v0h8x8a7iv',
  organizationId: 'cm9z9u0g30000r4v0h8x8a7na',
  key: 'DEFAULT_PAYROLL_INVOICE',
  name: 'Default Payroll Invoice Template',
  headerHtml: '<h1>Payroll Invoice</h1>',
  bodyHtml:
    '<div>Invoice No: {{invoiceNumber}}</div><div>Employee: {{employeeName}}</div><div>Total: {{grossAmount}}</div>',
  footerHtml: '<div>Generated by FlowForce HRM</div>',
  css: '.invoice { font-family: Arial; }',
  variables: {
    invoiceNumber: 'Invoice number',
    employeeName: 'Employee full name',
    grossAmount: 'Invoice total amount',
  },
  isDefault: true,
  isActive: true,
  createdAt: '2026-04-10T00:00:00.000Z',
  updatedAt: '2026-04-10T00:00:00.000Z',
};

@ApiTags('Invoice Templates')
@Controller('invoice-templates')
@UseGuards(JwtAuthGuard)
export class InvoiceTemplatesController {
  constructor(private readonly invoiceTemplatesService: InvoiceTemplatesService) {}

  @Post()
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.HR_MANAGER)
  @ApiOperation({ summary: 'Create an invoice template' })
  @ApiBearerAuth('access-token')
  @ApiBody({
    type: CreateInvoiceTemplateDto,
    examples: {
      createInvoiceTemplate: {
        summary: 'Create invoice template payload',
        value: createInvoiceTemplateExample,
      },
    },
  })
  @ApiCreatedResponse({
    description: 'Invoice template created successfully',
    type: InvoiceTemplateResponseDto,
    schema: { example: invoiceTemplateResponseExample },
  })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid access token' })
  @ApiForbiddenResponse({ description: 'Insufficient role permission' })
  async create(
    @Body() dto: CreateInvoiceTemplateDto,
    @Req() req: { user: { organizationId: string } },
  ): Promise<InvoiceTemplateResponseDto> {
    return (await this.invoiceTemplatesService.create(
      dto,
      req.user.organizationId,
    )) as InvoiceTemplateResponseDto;
  }

  @Get()
  @ApiOperation({ summary: 'List invoice templates' })
  @ApiQuery({
    name: 'organizationId',
    required: false,
    example: 'cm9z9u0g30000r4v0h8x8a7na',
  })
  @ApiQuery({
    name: 'key',
    required: false,
    example: 'DEFAULT_PAYROLL_INVOICE',
  })
  @ApiQuery({
    name: 'isDefault',
    required: false,
    example: true,
  })
  @ApiQuery({
    name: 'isActive',
    required: false,
    example: true,
  })
  @ApiOkResponse({
    description: 'Invoice template list',
    type: InvoiceTemplateResponseDto,
    isArray: true,
    schema: { example: [invoiceTemplateResponseExample] },
  })
  async findAll(
    @Query() query: InvoiceTemplateQueryDto,
    @Req() req: { user: { organizationId: string } },
  ): Promise<InvoiceTemplateResponseDto[]> {
    return (await this.invoiceTemplatesService.findAll(
      query,
      req.user.organizationId,
    )) as InvoiceTemplateResponseDto[];
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get invoice template by id' })
  @ApiParam({
    name: 'id',
    example: 'cm9z9u0g30000r4v0h8x8a7iv',
  })
  @ApiOkResponse({
    description: 'Invoice template details',
    type: InvoiceTemplateResponseDto,
    schema: { example: invoiceTemplateResponseExample },
  })
  async findOne(
    @Param('id') id: string,
    @Req() req: { user: { organizationId: string } },
  ): Promise<InvoiceTemplateResponseDto> {
    return (await this.invoiceTemplatesService.findOne(
      id,
      req.user.organizationId,
    )) as InvoiceTemplateResponseDto;
  }

  @Patch(':id')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.HR_MANAGER)
  @ApiOperation({ summary: 'Update invoice template by id' })
  @ApiBearerAuth('access-token')
  @ApiParam({
    name: 'id',
    example: 'cm9z9u0g30000r4v0h8x8a7iv',
  })
  @ApiBody({
    type: UpdateInvoiceTemplateDto,
    examples: {
      updateInvoiceTemplate: {
        summary: 'Update invoice template payload',
        value: {
          name: 'Modern Payroll Invoice Template',
          css: '.invoice { color: #111; }',
          isDefault: true,
          isActive: true,
        },
      },
    },
  })
  @ApiOkResponse({
    description: 'Invoice template updated successfully',
    type: InvoiceTemplateResponseDto,
    schema: {
      example: {
        ...invoiceTemplateResponseExample,
        name: 'Modern Payroll Invoice Template',
      },
    },
  })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid access token' })
  @ApiForbiddenResponse({ description: 'Insufficient role permission' })
  async update(
    @Param('id') id: string,
    @Body() dto: UpdateInvoiceTemplateDto,
    @Req() req: { user: { organizationId: string } },
  ): Promise<InvoiceTemplateResponseDto> {
    return (await this.invoiceTemplatesService.update(
      id,
      dto,
      req.user.organizationId,
    )) as InvoiceTemplateResponseDto;
  }

  @Delete(':id')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.HR_MANAGER)
  @ApiOperation({ summary: 'Delete invoice template by id' })
  @ApiBearerAuth('access-token')
  @ApiParam({
    name: 'id',
    example: 'cm9z9u0g30000r4v0h8x8a7iv',
  })
  @ApiOkResponse({
    description: 'Invoice template deleted successfully',
    type: DeleteInvoiceTemplateResponseDto,
    schema: {
      example: {
        deleted: true,
        id: 'cm9z9u0g30000r4v0h8x8a7iv',
      },
    },
  })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid access token' })
  @ApiForbiddenResponse({ description: 'Insufficient role permission' })
  remove(
    @Param('id') id: string,
    @Req() req: { user: { organizationId: string } },
  ): Promise<DeleteInvoiceTemplateResponseDto> {
    return this.invoiceTemplatesService.remove(id, req.user.organizationId);
  }
}
