import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsObject, IsOptional, IsString } from 'class-validator';

export class CreateInvoiceTemplateDto {
  @ApiProperty({ example: 'cm9z9u0g30000r4v0h8x8a7na' })
  @IsString()
  @IsNotEmpty()
  organizationId!: string;

  @ApiProperty({ example: 'DEFAULT_PAYROLL_INVOICE' })
  @IsString()
  @IsNotEmpty()
  key!: string;

  @ApiProperty({ example: 'Default Payroll Invoice Template' })
  @IsString()
  @IsNotEmpty()
  name!: string;

  @ApiPropertyOptional({ example: '<h1>Payroll Invoice</h1>' })
  @IsString()
  @IsOptional()
  headerHtml?: string;

  @ApiProperty({
    example:
      '<div>Invoice No: {{invoiceNumber}}</div><div>Employee: {{employeeName}}</div><div>Total: {{grossAmount}}</div>',
  })
  @IsString()
  @IsNotEmpty()
  bodyHtml!: string;

  @ApiPropertyOptional({ example: '<div>Generated by FlowForce HRM</div>' })
  @IsString()
  @IsOptional()
  footerHtml?: string;

  @ApiPropertyOptional({ example: '.invoice { font-family: Arial; }' })
  @IsString()
  @IsOptional()
  css?: string;

  @ApiPropertyOptional({
    example: {
      invoiceNumber: 'Invoice number',
      employeeName: 'Employee full name',
      grossAmount: 'Invoice total amount',
    },
  })
  @IsObject()
  @IsOptional()
  variables?: Record<string, unknown>;

  @ApiPropertyOptional({ example: false })
  @IsOptional()
  isDefault?: boolean;

  @ApiPropertyOptional({ example: true })
  @IsOptional()
  isActive?: boolean;
}
