import { ApiProperty } from '@nestjs/swagger';

export class InvoiceTemplateResponseDto {
  @ApiProperty({ example: 'cm9z9u0g30000r4v0h8x8a7iv' })
  id!: string;

  @ApiProperty({ example: 'cm9z9u0g30000r4v0h8x8a7na' })
  organizationId!: string;

  @ApiProperty({ example: 'DEFAULT_PAYROLL_INVOICE' })
  key!: string;

  @ApiProperty({ example: 'Default Payroll Invoice Template' })
  name!: string;

  @ApiProperty({ example: '<h1>Payroll Invoice</h1>', nullable: true })
  headerHtml!: string | null;

  @ApiProperty({
    example:
      '<div>Invoice No: {{invoiceNumber}}</div><div>Employee: {{employeeName}}</div><div>Total: {{grossAmount}}</div>',
  })
  bodyHtml!: string;

  @ApiProperty({ example: '<div>Generated by FlowForce HRM</div>', nullable: true })
  footerHtml!: string | null;

  @ApiProperty({ example: '.invoice { font-family: Arial; }', nullable: true })
  css!: string | null;

  @ApiProperty({
    example: {
      invoiceNumber: 'Invoice number',
      employeeName: 'Employee full name',
      grossAmount: 'Invoice total amount',
    },
    nullable: true,
  })
  variables!: Record<string, unknown> | null;

  @ApiProperty({ example: false })
  isDefault!: boolean;

  @ApiProperty({ example: true })
  isActive!: boolean;

  @ApiProperty({ example: '2026-04-10T00:00:00.000Z' })
  createdAt!: Date;

  @ApiProperty({ example: '2026-04-10T00:00:00.000Z' })
  updatedAt!: Date;
}

export class DeleteInvoiceTemplateResponseDto {
  @ApiProperty({ example: true })
  deleted!: boolean;

  @ApiProperty({ example: 'cm9z9u0g30000r4v0h8x8a7iv' })
  id!: string;
}
