type OpenApiSchema = {
  $ref?: string;
  type?: string;
  format?: string;
  example?: unknown;
  default?: unknown;
  enum?: unknown[];
  items?: OpenApiSchema;
  properties?: Record<string, OpenApiSchema>;
  required?: string[];
  allOf?: OpenApiSchema[];
  oneOf?: OpenApiSchema[];
  anyOf?: OpenApiSchema[];
  additionalProperties?: OpenApiSchema | boolean;
};

type OpenApiMediaType = {
  schema?: OpenApiSchema;
  example?: unknown;
  examples?: Record<string, { summary?: string; value: unknown }>;
};

type OpenApiRequestBody = {
  content?: Record<string, OpenApiMediaType>;
};

type OpenApiResponse = {
  description?: string;
  content?: Record<string, OpenApiMediaType>;
};

type OpenApiOperation = {
  requestBody?: OpenApiRequestBody;
  responses?: Record<string, OpenApiResponse>;
};

type OpenApiPathItem = Partial<
  Record<'get' | 'post' | 'put' | 'patch' | 'delete', OpenApiOperation>
>;

type OpenApiDocument = {
  paths?: Record<string, OpenApiPathItem>;
  components?: {
    schemas?: Record<string, OpenApiSchema>;
  };
};

const METHODS: Array<'get' | 'post' | 'put' | 'patch' | 'delete'> = [
  'get',
  'post',
  'put',
  'patch',
  'delete',
];

export function addAutoExamplesToDocument(document: unknown): void {
  const openApiDocument = document as OpenApiDocument;
  const paths = openApiDocument.paths ?? {};

  for (const pathItem of Object.values(paths)) {
    for (const method of METHODS) {
      const operation = pathItem[method];
      if (!operation) continue;

      const requestExample = ensureRequestExample(operation, openApiDocument);
      ensureResponseExamples(operation, method, requestExample, openApiDocument);
    }
  }
}

function ensureRequestExample(
  operation: OpenApiOperation,
  document: OpenApiDocument,
): unknown {
  const requestBody = operation.requestBody;
  const media = requestBody?.content?.['application/json'];
  if (!media) return undefined;

  if (media.example !== undefined) return media.example;

  if (media.examples && Object.keys(media.examples).length > 0) {
    const firstExample = Object.values(media.examples)[0];
    return firstExample?.value;
  }

  const generated = buildExample(media.schema, document);
  if (generated === undefined) return undefined;

  media.examples = {
    autoGenerated: {
      summary: 'Auto-generated example',
      value: generated,
    },
  };

  return generated;
}

function ensureResponseExamples(
  operation: OpenApiOperation,
  method: 'get' | 'post' | 'put' | 'patch' | 'delete',
  requestExample: unknown,
  document: OpenApiDocument,
): void {
  operation.responses ??= {};

  const successCode = method === 'post' ? '201' : '200';
  if (!operation.responses[successCode]) {
    operation.responses[successCode] = {
      description: 'Success',
      content: {
        'application/json': {
          examples: {
            autoGenerated: {
              summary: 'Auto-generated response',
              value: fallbackResponseExample(method, requestExample),
            },
          },
        },
      },
    };
  }

  for (const [statusCode, response] of Object.entries(operation.responses)) {
    if (!statusCode.startsWith('2')) continue;

    response.content ??= {};
    response.content['application/json'] ??= {};

    const media = response.content['application/json'];
    if (media.example !== undefined) continue;
    if (media.examples && Object.keys(media.examples).length > 0) continue;

    const fromSchema = buildExample(media.schema, document);
    const value =
      fromSchema ??
      fallbackResponseExample(method, requestExample) ??
      ({ success: true } as unknown);

    media.examples = {
      autoGenerated: {
        summary: 'Auto-generated response',
        value,
      },
    };
  }
}

function fallbackResponseExample(
  method: 'get' | 'post' | 'put' | 'patch' | 'delete',
  requestExample: unknown,
): unknown {
  if (method === 'delete') {
    return { deleted: true, id: 'example-id' };
  }

  if (requestExample && typeof requestExample === 'object') {
    return {
      ...(requestExample as Record<string, unknown>),
      id: 'example-id',
    };
  }

  if (method === 'get') {
    return { message: 'OK' };
  }

  return { success: true };
}

function buildExample(
  schema: OpenApiSchema | undefined,
  document: OpenApiDocument,
  depth = 0,
): unknown {
  if (!schema || depth > 7) return undefined;

  if (schema.$ref) {
    const resolved = resolveRef(schema.$ref, document);
    return buildExample(resolved, document, depth + 1);
  }

  if (schema.example !== undefined) return schema.example;
  if (schema.default !== undefined) return schema.default;

  if (schema.allOf && schema.allOf.length > 0) {
    const merged: Record<string, unknown> = {};
    for (const item of schema.allOf) {
      const value = buildExample(item, document, depth + 1);
      if (value && typeof value === 'object' && !Array.isArray(value)) {
        Object.assign(merged, value as Record<string, unknown>);
      }
    }
    return Object.keys(merged).length > 0 ? merged : undefined;
  }

  const composite = schema.oneOf ?? schema.anyOf;
  if (composite && composite.length > 0) {
    return buildExample(composite[0], document, depth + 1);
  }

  if (schema.enum && schema.enum.length > 0) {
    return schema.enum[0];
  }

  const type = schema.type;
  if (type === 'array') {
    const item = buildExample(schema.items, document, depth + 1);
    return item === undefined ? [] : [item];
  }

  if (type === 'object' || schema.properties) {
    const example: Record<string, unknown> = {};
    for (const [key, propSchema] of Object.entries(schema.properties ?? {})) {
      const value = buildExample(propSchema, document, depth + 1);
      if (value !== undefined) {
        example[key] = value;
      }
    }

    if (Object.keys(example).length > 0) {
      return example;
    }

    if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
      const additional = buildExample(
        schema.additionalProperties,
        document,
        depth + 1,
      );
      return { key: additional ?? 'value' };
    }

    return {};
  }

  if (type === 'string') {
    if (schema.format === 'date-time') return '2026-04-10T00:00:00.000Z';
    if (schema.format === 'date') return '2026-04-10';
    if (schema.format === 'email') return 'user@example.com';
    if (schema.format === 'uuid') return '123e4567-e89b-12d3-a456-426614174000';
    return 'string';
  }

  if (type === 'integer') return 1;
  if (type === 'number') return 1.5;
  if (type === 'boolean') return true;

  return undefined;
}

function resolveRef(ref: string, document: OpenApiDocument): OpenApiSchema | undefined {
  const prefix = '#/components/schemas/';
  if (!ref.startsWith(prefix)) return undefined;

  const schemaName = ref.slice(prefix.length);
  return document.components?.schemas?.[schemaName];
}
